redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/dirksen/DPS/polis/netlify"
publishOrigin = "default"
base = "/Users/dirksen/DPS/polis/netlify"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "http://34.130.138.24/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]